name: Update credly badges

on:
  schedule:
    # Runs at 14:15 UTC
    - cron: "15 14 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: sync credly badges
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # REPOSITORY: <username>/<username> # optional, By default, it will automatically use the repository who's executing the workflow.
          COMMIT_MESSAGE: "ci(credly): update badges" # optional
          # CREDLY_USER: <username_credly> # optional, but default will use the same from github
          CREDLY_SORT: POPULAR  #RECENT or POPULAR # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
          BADGE_SIZE: 65 # the resolution to the badges images # optional, 110x110 default
          NUMBER_LAST_BADGES: 15 # the maximum last badges to show # optional, will show the 48 in the first page