name: Update WakaTime stats

on:
  schedule:
    # Runs at 22:30 UTC
    - cron: "30 22 * * *"
jobs:
  update-waka-weekly:
    name: Update metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TIME: true
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_30_days
          SHOW_TOTAL: false
          SECTION_NAME: wakaweek
          COMMIT_MESSAGE: "ci(wakatime): update monthly stat"
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TIME: true
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_7_days
          SHOW_TOTAL: false
          SECTION_NAME: wakaweek
          COMMIT_MESSAGE: "ci(wakatime): update weekly stat"
    